<?php

use Illuminate\Database\Seeder;

class ReviewsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      DB::table('reviews')->delete();

        DB::table('reviews')->insert([
      array('id' => '1','reservation_id' => '10020','space_id' => '10018','user_from' => '10004','user_to' => '10002','review_by' => 'guest','comments' => 'Space was better than amazing!!! It had everything we needed to create a perfect event!!! Thank you!!!','private_feedback' => '','love_comments' => 'Space is good ','improve_comments' => 'Can appoint some guards ','rating' => '4','accuracy' => '4','accuracy_comments' => 'Good ','cleanliness' => '4','cleanliness_comments' => 'Excellent ','checkin' => '4','checkin_comments' => '','amenities' => '4','amenities_comments' => '','communication' => '4','communication_comments' => '','location' => '4','location_comments' => '','value' => '4','value_comments' => '','respect_house_rules' => '0','recommend' => '1','created_at' => '2019-10-22 11:48:47','updated_at' => '2019-10-22 11:49:22'),
      array('id' => '2','reservation_id' => '10019','space_id' => '10015','user_from' => '10004','user_to' => '10003','review_by' => 'guest','comments' => 'Incredible versatility and accommodating space. Many areas for content and a parking garage right next door. So helpful that it had many pieces of lighting gear for us to utilize.','private_feedback' => '','love_comments' => 'Polite owner ','improve_comments' => 'No need','rating' => '4','accuracy' => '4','accuracy_comments' => '','cleanliness' => '3','cleanliness_comments' => '','checkin' => '4','checkin_comments' => '','amenities' => '3','amenities_comments' => '','communication' => '4','communication_comments' => '','location' => '4','location_comments' => '','value' => '4','value_comments' => 'Worth of money','respect_house_rules' => '0','recommend' => '1','created_at' => '2019-10-22 11:50:13','updated_at' => '2019-10-22 11:52:56'),
      array('id' => '3','reservation_id' => '10018','space_id' => '10004','user_from' => '10004','user_to' => '10002','review_by' => 'host','comments' => 'She used this space very well . Good job !!!','private_feedback' => 'Nice to meet you.','love_comments' => '','improve_comments' => '','rating' => '0','accuracy' => '0','accuracy_comments' => '','cleanliness' => '4','cleanliness_comments' => '','checkin' => '0','checkin_comments' => '','amenities' => '0','amenities_comments' => '','communication' => '4','communication_comments' => '','location' => '0','location_comments' => '','value' => '0','value_comments' => '','respect_house_rules' => '4','recommend' => '1','created_at' => '2019-10-22 11:54:34','updated_at' => '2019-10-22 11:54:34'),
      array('id' => '4','reservation_id' => '10023','space_id' => '10005','user_from' => '10004','user_to' => '10001','review_by' => 'host','comments' => 'Enjoyed their event along with the audience , such good vibes !!','private_feedback' => 'Thank you','love_comments' => '','improve_comments' => '','rating' => '0','accuracy' => '0','accuracy_comments' => '','cleanliness' => '4','cleanliness_comments' => '','checkin' => '0','checkin_comments' => '','amenities' => '0','amenities_comments' => '','communication' => '3','communication_comments' => '','location' => '0','location_comments' => '','value' => '0','value_comments' => '','respect_house_rules' => '4','recommend' => '1','created_at' => '2019-10-22 11:56:05','updated_at' => '2019-10-22 11:56:05'),
      array('id' => '5','reservation_id' => '10022','space_id' => '10011','user_from' => '10003','user_to' => '10001','review_by' => 'guest','comments' => 'An amazing space and brilliant host! Thank you so much Mick! Looking forward to the next time we may work together! ','private_feedback' => '','love_comments' => 'Thanks','improve_comments' => 'No need ','rating' => '3','accuracy' => '4','accuracy_comments' => '','cleanliness' => '4','cleanliness_comments' => '','checkin' => '3','checkin_comments' => '','amenities' => '4','amenities_comments' => '','communication' => '5','communication_comments' => '','location' => '5','location_comments' => '','value' => '4','value_comments' => '','respect_house_rules' => '0','recommend' => '1','created_at' => '2019-10-22 11:57:26','updated_at' => '2019-10-22 11:57:41'),
      array('id' => '6','reservation_id' => '10021','space_id' => '10009','user_from' => '10003','user_to' => '10002','review_by' => 'guest','comments' => 'Amazing host and very attentive. Helped through every step of the way!','private_feedback' => '','love_comments' => 'Thanks','improve_comments' => 'No need for .','rating' => '5','accuracy' => '4','accuracy_comments' => '','cleanliness' => '4','cleanliness_comments' => '','checkin' => '3','checkin_comments' => '','amenities' => '4','amenities_comments' => '','communication' => '3','communication_comments' => '','location' => '5','location_comments' => '','value' => '4','value_comments' => '','respect_house_rules' => '0','recommend' => '1','created_at' => '2019-10-22 11:58:37','updated_at' => '2019-10-22 11:58:49'),
      array('id' => '7','reservation_id' => '10019','space_id' => '10015','user_from' => '10003','user_to' => '10004','review_by' => 'host','comments' => 'Young talents , used this space very well and gained more knowledge from them ! Thanks guys .','private_feedback' => 'Excellent','love_comments' => '','improve_comments' => '','rating' => '0','accuracy' => '0','accuracy_comments' => '','cleanliness' => '4','cleanliness_comments' => '','checkin' => '0','checkin_comments' => '','amenities' => '0','amenities_comments' => '','communication' => '4','communication_comments' => '','location' => '0','location_comments' => '','value' => '0','value_comments' => '','respect_house_rules' => '4','recommend' => '1','created_at' => '2019-10-22 12:00:26','updated_at' => '2019-10-22 12:00:26'),
      array('id' => '8','reservation_id' => '10024','space_id' => '10013','user_from' => '10003','user_to' => '10001','review_by' => 'host','comments' => 'John is such a polite person , working with him was so good and energetic . Thanks ','private_feedback' => 'Thanks ','love_comments' => '','improve_comments' => '','rating' => '0','accuracy' => '0','accuracy_comments' => '','cleanliness' => '4','cleanliness_comments' => '','checkin' => '0','checkin_comments' => '','amenities' => '0','amenities_comments' => '','communication' => '5','communication_comments' => '','location' => '0','location_comments' => '','value' => '0','value_comments' => '','respect_house_rules' => '4','recommend' => '1','created_at' => '2019-10-22 12:01:30','updated_at' => '2019-10-22 12:01:30'),
      array('id' => '9','reservation_id' => '10024','space_id' => '10013','user_from' => '10001','user_to' => '10003','review_by' => 'guest','comments' => 'We had a wonderful time doing our wedding ceremony and reception here. A big thank you to Mick for being so accommodating and communicative leading up to the event. The space is gorgeous and exceeded all expectations!','private_feedback' => '','love_comments' => 'Thanks man ','improve_comments' => 'Good ','rating' => '5','accuracy' => '4','accuracy_comments' => '','cleanliness' => '4','cleanliness_comments' => '','checkin' => '4','checkin_comments' => '','amenities' => '4','amenities_comments' => '','communication' => '4','communication_comments' => '','location' => '5','location_comments' => '','value' => '5','value_comments' => '','respect_house_rules' => '0','recommend' => '1','created_at' => '2019-10-22 12:02:48','updated_at' => '2019-10-22 12:03:02'),
      array('id' => '10','reservation_id' => '10023','space_id' => '10005','user_from' => '10001','user_to' => '10004','review_by' => 'guest','comments' => 'Trioangle was an incredible host! He answered all of our questions whether we called or emailed him leading up to our event. The space was in great shape upon our arrival and we were given detailed instructions that made for an easy clean up. He was also on site to help with the use of the sound system, rooftop lights and wifi. Our guests were in love with the loft, its unique style and openness allowed for us to host 150 people with catering and a full bar. ','private_feedback' => '','love_comments' => 'Keep it up man','improve_comments' => 'No need ','rating' => '4','accuracy' => '5','accuracy_comments' => '','cleanliness' => '4','cleanliness_comments' => '','checkin' => '5','checkin_comments' => '','amenities' => '3','amenities_comments' => '','communication' => '5','communication_comments' => '','location' => '4','location_comments' => '','value' => '5','value_comments' => '','respect_house_rules' => '0','recommend' => '1','created_at' => '2019-10-22 12:04:54','updated_at' => '2019-10-22 12:05:07'),
      array('id' => '11','reservation_id' => '10017','space_id' => '10012','user_from' => '10001','user_to' => '10002','review_by' => 'host','comments' => 'She is a good event organizer , left my space clean . Thanks a lot.','private_feedback' => 'Thanks ','love_comments' => '','improve_comments' => '','rating' => '0','accuracy' => '0','accuracy_comments' => '','cleanliness' => '4','cleanliness_comments' => '','checkin' => '0','checkin_comments' => '','amenities' => '0','amenities_comments' => '','communication' => '4','communication_comments' => '','location' => '0','location_comments' => '','value' => '0','value_comments' => '','respect_house_rules' => '5','recommend' => '1','created_at' => '2019-10-22 12:06:23','updated_at' => '2019-10-22 12:06:23'),
      array('id' => '12','reservation_id' => '10022','space_id' => '10011','user_from' => '10001','user_to' => '10003','review_by' => 'host','comments' => 'Mick is great event organizer , his team was good and polite .','private_feedback' => 'Good job man ','love_comments' => '','improve_comments' => '','rating' => '0','accuracy' => '0','accuracy_comments' => '','cleanliness' => '4','cleanliness_comments' => '','checkin' => '0','checkin_comments' => '','amenities' => '0','amenities_comments' => '','communication' => '5','communication_comments' => '','location' => '0','location_comments' => '','value' => '0','value_comments' => '','respect_house_rules' => '4','recommend' => '1','created_at' => '2019-10-22 12:07:18','updated_at' => '2019-10-22 12:07:18'),
      array('id' => '13','reservation_id' => '10018','space_id' => '10004','user_from' => '10002','user_to' => '10004','review_by' => 'guest','comments' => 'Trioangle was very helpful and communicative in the booking process and lead up to our event. Many of the attendees commented on how cool the space was. I liked that it had multiple areas, which gave the event a very spacious feel. He was also super helpful on the day of, running out to replenish paper towels etc. for the bathroom / kitchen area, changing around the projector etc.','private_feedback' => '','love_comments' => 'Great job man ','improve_comments' => 'No need ','rating' => '5','accuracy' => '4','accuracy_comments' => '','cleanliness' => '5','cleanliness_comments' => '','checkin' => '4','checkin_comments' => '','amenities' => '4','amenities_comments' => '','communication' => '5','communication_comments' => '','location' => '4','location_comments' => '','value' => '5','value_comments' => '','respect_house_rules' => '0','recommend' => '1','created_at' => '2019-10-22 12:09:41','updated_at' => '2019-10-22 12:09:53'),
      array('id' => '14','reservation_id' => '10017','space_id' => '10012','user_from' => '10002','user_to' => '10001','review_by' => 'guest','comments' => 'John was a great host with excellent catering. Overall, an easy event and hope to work together again soon.','private_feedback' => '','love_comments' => 'Great job man ','improve_comments' => 'Thanks ','rating' => '4','accuracy' => '4','accuracy_comments' => '','cleanliness' => '3','cleanliness_comments' => '','checkin' => '4','checkin_comments' => '','amenities' => '4','amenities_comments' => '','communication' => '4','communication_comments' => '','location' => '4','location_comments' => '','value' => '4','value_comments' => '','respect_house_rules' => '0','recommend' => '1','created_at' => '2019-10-22 12:10:49','updated_at' => '2019-10-22 12:11:02'),
      array('id' => '15','reservation_id' => '10020','space_id' => '10018','user_from' => '10002','user_to' => '10004','review_by' => 'host','comments' => 'Trioangle is a good organizer with mass audience response , Loved to work with him. Hope to meet you next time','private_feedback' => 'Good ','love_comments' => '','improve_comments' => '','rating' => '0','accuracy' => '0','accuracy_comments' => '','cleanliness' => '4','cleanliness_comments' => '','checkin' => '0','checkin_comments' => '','amenities' => '0','amenities_comments' => '','communication' => '5','communication_comments' => '','location' => '0','location_comments' => '','value' => '0','value_comments' => '','respect_house_rules' => '4','recommend' => '1','created_at' => '2019-10-22 12:12:44','updated_at' => '2019-10-22 12:12:44'),
      array('id' => '16','reservation_id' => '10021','space_id' => '10009','user_from' => '10002','user_to' => '10003','review_by' => 'host','comments' => 'Mick has a wonderful team , they maintained the space clean and used the space very well!!','private_feedback' => 'Thanks','love_comments' => '','improve_comments' => '','rating' => '0','accuracy' => '0','accuracy_comments' => '','cleanliness' => '4','cleanliness_comments' => '','checkin' => '0','checkin_comments' => '','amenities' => '0','amenities_comments' => '','communication' => '4','communication_comments' => '','location' => '0','location_comments' => '','value' => '0','value_comments' => '','respect_house_rules' => '5','recommend' => '1','created_at' => '2019-10-22 12:15:45','updated_at' => '2019-10-22 12:15:45'),
        ]);
    }
}