<?php

use Illuminate\Database\Seeder;

class RoomsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('rooms')->delete();
        DB::table('rooms_beds')->delete();
    	
        DB::table('rooms')->insert([

        		['id' => '10001','user_id' => '10001','name' => 'Charming Studio Ile Saint-Louis','sub_name' => 'Shared room in London','summary' => 'First choice location in the very heart of Paris. Enjoy this welcoming studio fully equipped to cater to your needs. Featuring a large living area with double sofa bed, an open kitchen and a shower room with toilet. Ideal for a romantic stay in Paris','check_in_time' => 'Flexible','check_out_time' => 'Flexible','booking_message' => '','property_type' => '3','room_type' => '3','accommodates' => '9','bedrooms' => '4','beds' => '8','bed_type' => '3','bathrooms' => '3.5','amenities' => '1,2,4,6,7,13,15,21,23,30','video' => '','calendar_type' => 'Always','booking_type' => NULL,'cancel_policy' => 'Flexible','popular' => 'No','started' => 'Yes','recommended' => 'Yes','views_count' => '0','status' => 'Listed','verified' => 'Approved','created_at' => '2017-08-14 07:25:57','updated_at' => '2017-08-14 12:09:26','deleted_at' => NULL, 'is_shared' => 'Yes'],
            ['id' => '10002','user_id' => '10001','name' => '','sub_name' => 'Entire home/apt in ','summary' => '','check_in_time' => 'Flexible','check_out_time' => 'Flexible','booking_message' => '','property_type' => '2','room_type' => '1','accommodates' => '8','bedrooms' => NULL,'beds' => NULL,'bed_type' => NULL,'bathrooms' => NULL,'amenities' => NULL,'video' => '','calendar_type' => NULL,'booking_type' => NULL,'cancel_policy' => 'Flexible','popular' => 'No','started' => 'No','recommended' => 'No','views_count' => '0','status' => NULL,'verified' => 'Pending','created_at' => '2017-08-14 08:47:35','updated_at' => '2017-08-14 08:47:35','deleted_at' => NULL, 'is_shared' => 'No'],
            ['id' => '10003','user_id' => '10001','name' => 'Chambre accueillante chezl habitant','sub_name' => 'Entire home/apt in ','summary' => 'Chambre dans un appartement en hauteur, 7 min du métro Marcel Sembat L9, idéale pour un passage à Paris. L appartement dispose d une salle de bain, wc, cuisine et un salon à votre disposition, à partager avec nous (Anna, Alex, 30 ans et Biscotte, petit carlin de 2 ans). Nous nous ferons une joie de vous accueillir chez nous et de répondre à toutes vos questions et curiosités :)','check_in_time' => 'Flexible','check_out_time' => 'Flexible','booking_message' => '','property_type' => '2','room_type' => '1','accommodates' => '8','bedrooms' => '4','beds' => '6','bed_type' => '5','bathrooms' => '2.0','amenities' => '1,2,4,6,7,8,10,13,21,24,29,30','video' => '','calendar_type' => 'Always','booking_type' => 'instant_book','cancel_policy' => 'Flexible','popular' => 'Yes','started' => 'Yes','recommended' => 'No','views_count' => '1','status' => 'Listed','verified' => 'Approved','created_at' => '2017-08-14 08:48:22','updated_at' => '2017-08-17 13:11:40','deleted_at' => NULL, 'is_shared' => 'No'],
            ['id' => '10004','user_id' => '10001','name' => 'Cozy room in center of Park Slope','sub_name' => 'Entire home/apt in Jersey City','summary' => 'Cozy air conditioned room in owner occupied house in the heart of Park Slope. Shared bathroom with shower/bath tub. Steps away from restaurants/bars and shopping. Within walking distance of major subway lines, Prospect Park, BAM and Barclay Center.','check_in_time' => 'Flexible','check_out_time' => 'Flexible','booking_message' => '','property_type' => '3','room_type' => '1','accommodates' => '9','bedrooms' => '5','beds' => '8','bed_type' => '2','bathrooms' => '2.5','amenities' => '4,6,7,8,15,21,23,24,25,26','video' => '','calendar_type' => 'Always','booking_type' => NULL,'cancel_policy' => 'Flexible','popular' => 'Yes','started' => 'Yes','recommended' => 'Yes','views_count' => '2','status' => 'Listed','verified' => 'Approved','created_at' => '2017-08-14 09:54:09','updated_at' => '2017-08-21 10:10:15','deleted_at' => NULL, 'is_shared' => 'No'],
            ['id' => '10005','user_id' => '10001','name' => 'Right by the Thames with Great View','sub_name' => 'Entire home/apt in ','summary' => 'Double bedroom in 4 bedroom townhouse located on the banks of the river Thames. There are fantastic views of Tower Bridge from the living room balcony. The Thames Path is 1 minute away, offering access to Tate Modern, Tower Bridge or Greenwich','check_in_time' => 'Flexible','check_out_time' => 'Flexible','booking_message' => '','property_type' => '1','room_type' => '1','accommodates' => '6','bedrooms' => '3','beds' => '6','bed_type' => '3','bathrooms' => '2.0','amenities' => '2,5,6,8,11,13,15,21,23,24,26,27,30,31','video' => '','calendar_type' => 'Always','booking_type' => NULL,'cancel_policy' => 'Flexible','popular' => 'Yes','started' => 'Yes','recommended' => 'No','views_count' => '1','status' => 'Listed','verified' => 'Approved','created_at' => '2017-08-14 10:20:37','updated_at' => '2017-08-21 10:17:44','deleted_at' => NULL, 'is_shared' => 'No'],
            ['id' => '10006','user_id' => '10002','name' => 'Elegant studio near by the castle','sub_name' => 'Private room in Budapest','summary' => 'Be a downtown citizen of Budapest for a little time!:)Come and learn more about the Budapest mainstream lifestyle in this built in 1910 house.The studio has got a rustically elegant design,and its a comfortable,quiet home in the center','check_in_time' => 'Flexible','check_out_time' => 'Flexible','booking_message' => '','property_type' => '3','room_type' => '2','accommodates' => '5','bedrooms' => '5','beds' => '6','bed_type' => '4','bathrooms' => '2.5','amenities' => '1,5,6,7,12,13,15,21,26,27,28','video' => '','calendar_type' => 'Always','booking_type' => 'instant_book','cancel_policy' => 'Flexible','popular' => 'Yes','started' => 'Yes','recommended' => 'Yes','views_count' => '2','status' => 'Listed','verified' => 'Approved','created_at' => '2017-08-14 10:40:42','updated_at' => '2017-08-17 07:12:09','deleted_at' => NULL, 'is_shared' => 'No'],
            ['id' => '10007','user_id' => '10002','name' => 'CHAMPS ELYSEES APARTMENT','sub_name' => 'Private room in Paris','summary' => 'A very nice, luminous and design loft that was entirely refurbished in 2015, located in the heart of Saint-Germain-des-Prés, at 100m of Jardin du Luxembourg. The appartment is located on the 1st floor of a traditional Parisian building.','check_in_time' => 'Flexible','check_out_time' => 'Flexible','booking_message' => '','property_type' => '1','room_type' => '2','accommodates' => '11','bedrooms' => '4','beds' => '5','bed_type' => '2','bathrooms' => '2.0','amenities' => '4,6,7,8,13,15,21,24,30','video' => '','calendar_type' => 'Always','booking_type' => NULL,'cancel_policy' => 'Flexible','popular' => 'Yes','started' => 'Yes','recommended' => 'No','views_count' => '2','status' => 'Listed','verified' => 'Approved','created_at' => '2017-08-14 10:42:57','updated_at' => '2017-08-21 10:13:10','deleted_at' => NULL, 'is_shared' => 'No'],
            ['id' => '10008','user_id' => '10002','name' => 'Cozy Room in Brooklyn','sub_name' => 'Private room in Cherry Hill','summary' => 'Small Room. Steps away from the 3 train. A few short blocks from Franklin Ave which has tons of great restaurants and bars. Walking distance to Prospect Park and Botanical gardens.','check_in_time' => 'Flexible','check_out_time' => 'Flexible','booking_message' => '','property_type' => '3','room_type' => '2','accommodates' => '12','bedrooms' => '4','beds' => '8','bed_type' => '3','bathrooms' => '2.5','amenities' => '2,3,4,5,7,8,16,17,21,23,28,29,30','video' => '','calendar_type' => 'Always','booking_type' => NULL,'cancel_policy' => 'Flexible','popular' => 'No','started' => 'Yes','recommended' => 'Yes','views_count' => '2','status' => 'Listed','verified' => 'Approved','created_at' => '2017-08-14 10:45:11','updated_at' => '2017-08-17 13:15:49','deleted_at' => NULL, 'is_shared' => 'No'],
            ['id' => '10009','user_id' => '10003','name' => '','sub_name' => 'Shared room in ','summary' => '','check_in_time' => 'Flexible','check_out_time' => 'Flexible','booking_message' => '','property_type' => '2','room_type' => '3','accommodates' => '10','bedrooms' => '4','beds' => '8','bed_type' => '1','bathrooms' => '2.0','amenities' => NULL,'video' => '','calendar_type' => 'Always','booking_type' => NULL,'cancel_policy' => 'Flexible','popular' => 'No','started' => 'Yes','recommended' => 'No','views_count' => '0','status' => NULL,'verified' => 'Pending','created_at' => '2017-08-14 10:48:50','updated_at' => '2017-08-14 10:50:05','deleted_at' => NULL, 'is_shared' => 'Yes'],
            ['id' => '10010','user_id' => '10003','name' => 'loooft Barcelona!','sub_name' => 'Entire home/apt in Sabadell','summary' => 'This light room-loft is perfect for couples or single travelers who love terraces and opened air. Ideal for those who value space and quality with a competitive price.','check_in_time' => 'Flexible','check_out_time' => 'Flexible','booking_message' => '','property_type' => '2','room_type' => '1','accommodates' => '5','bedrooms' => '4','beds' => '7','bed_type' => '2','bathrooms' => '2.0','amenities' => '1,2,3,4,6,7,10,12,13,21,23','video' => '','calendar_type' => 'Always','booking_type' => NULL,'cancel_policy' => 'Flexible','popular' => 'Yes','started' => 'Yes','recommended' => 'No','views_count' => '1','status' => 'Listed','verified' => 'Approved','created_at' => '2017-08-14 10:50:41','updated_at' => '2017-08-17 13:16:46','deleted_at' => NULL, 'is_shared' => 'No'],
            ['id' => '10011','user_id' => '10003','name' => 'Charming double bedroom in Richmond','sub_name' => 'Entire home/apt in Bensalem','summary' => 'Charming double garden room in two bed flat with home owner. 5mins from Richmond station, Hill and town, 20 mins into Waterloo and easy access to central London.','check_in_time' => 'Flexible','check_out_time' => 'Flexible','booking_message' => '','property_type' => '3','room_type' => '1','accommodates' => '13','bedrooms' => '4','beds' => '5','bed_type' => '3','bathrooms' => '3.5','amenities' => '1,3,4,5,8,13,15,21,23,24,25,26,28,29,30','video' => '','calendar_type' => 'Always','booking_type' => NULL,'cancel_policy' => 'Flexible','popular' => 'No','started' => 'Yes','recommended' => 'Yes','views_count' => '2','status' => 'Listed','verified' => 'Approved','created_at' => '2017-08-14 10:52:37','updated_at' => '2017-08-17 12:29:44','deleted_at' => NULL, 'is_shared' => 'No'],
            ['id' => '10012','user_id' => '10003','name' => 'large, comfy br in fun neighborhood','sub_name' => 'Entire home/apt in New York','summary' => 'large, comfortable bedroom in the heart of the mission district, the best neighborhood in san francisco! walk to awesome restaurants or bart downtown. with a park right in front and a beautiful sunny garden in back. room is for one person only.','check_in_time' => 'Flexible','check_out_time' => 'Flexible','booking_message' => '','property_type' => '1','room_type' => '1','accommodates' => '8','bedrooms' => '3','beds' => '4','bed_type' => '1','bathrooms' => '2.0','amenities' => '1,2,3,4,5,9,10,11,12,23,24,25,30','video' => '','calendar_type' => 'Always','booking_type' => NULL,'cancel_policy' => 'Flexible','popular' => 'Yes','started' => 'Yes','recommended' => 'Yes','views_count' => '1','status' => 'Listed','verified' => 'Approved','created_at' => '2017-08-14 10:54:27','updated_at' => '2017-08-17 14:34:08','deleted_at' => NULL, 'is_shared' => 'No'],
            ['id' => '10013','user_id' => '10004','name' => 'Studio with lake view','sub_name' => 'Private room in Berlin','summary' => 'Studio with view at Lake Rummelsburg and the Skyline of Berlin, including the TV tower. There are two convenient sofa beds for three people and a lot of space for sleeping mats…\\nIMPORTANT: The office must be possible to use occasionally!','check_in_time' => 'Flexible','check_out_time' => 'Flexible','booking_message' => '','property_type' => '2','room_type' => '2','accommodates' => '6','bedrooms' => '4','beds' => '5','bed_type' => '4','bathrooms' => '2.5','amenities' => '1,4,5,6,7,8,12,13,15,21,23,24,25,29,30,31','video' => '','calendar_type' => 'Always','booking_type' => NULL,'cancel_policy' => 'Flexible','popular' => 'Yes','started' => 'Yes','recommended' => 'No','views_count' => '2','status' => 'Listed','verified' => 'Approved','created_at' => '2017-08-14 11:12:34','updated_at' => '2017-08-17 13:13:24','deleted_at' => NULL, 'is_shared' => 'No'],
            ['id' => '10014','user_id' => '10004','name' => 'Haleakala B&B-Aloha Rm / Prvt Entry','sub_name' => 'Private room in Kailua-Kona','summary' => 'Haleakala Bed & Breakfast is surrounded by Macadamia Orchards and Coffee groves providing a natural setting for many of Hawaii birds and game fowl. You will enjoy the unfettered views of the Western Pacific Ocean & Sunsets from the Main Lanai.','check_in_time' => 'Flexible','check_out_time' => 'Flexible','booking_message' => '','property_type' => '1','room_type' => '2','accommodates' => '7','bedrooms' => '3','beds' => '5','bed_type' => '3','bathrooms' => '2.5','amenities' => '5,6,7,8,12,13,15,21,22,24,25,28,31','video' => '','calendar_type' => 'Always','booking_type' => NULL,'cancel_policy' => 'Flexible','popular' => 'Yes','started' => 'Yes','recommended' => 'No','views_count' => '0','status' => 'Listed','verified' => 'Approved','created_at' => '2017-08-14 11:14:36','updated_at' => '2017-08-14 12:08:09','deleted_at' => NULL, 'is_shared' => 'No'],
            ['id' => '10015','user_id' => '10004','name' => 'Beautiful brownstone room','sub_name' => 'Private room in New York','summary' => 'Beautiful brownstone room is located in the center of Brooklyn, where everything is is possible . Good delicious , spicey food ,a friendly rainbow mixture of all races , Brooklyn botanical garden , prospect park , Brooklyn children Museum','check_in_time' => 'Flexible','check_out_time' => 'Flexible','booking_message' => '','property_type' => '2','room_type' => '2','accommodates' => '12','bedrooms' => '4','beds' => '6','bed_type' => '3','bathrooms' => '2.0','amenities' => NULL,'video' => '','calendar_type' => 'Always','booking_type' => NULL,'cancel_policy' => 'Flexible','popular' => 'Yes','started' => 'Yes','recommended' => 'No','views_count' => '7','status' => 'Listed','verified' => 'Approved','created_at' => '2017-08-14 11:16:35','updated_at' => '2017-08-21 10:12:30','deleted_at' => NULL, 'is_shared' => 'No'],
            ['id' => '10016','user_id' => '10004','name' => 'LUXURY Room','sub_name' => 'Shared room in Christchurch','summary' => 'Large, bright room in an AMAZING 2500 sq ft warehouse apartment in the worlds first dog food factory! Only 4 stops (6 mins) to Canary Wharf! Features a huge kitchen, luxury bathroom, 2 balconies, roof terrace, BBQ, and a full-body massage chair!','check_in_time' => 'Flexible','check_out_time' => 'Flexible','booking_message' => '','property_type' => '2','room_type' => '3','accommodates' => '13','bedrooms' => '5','beds' => '7','bed_type' => '2','bathrooms' => '2.0','amenities' => '1,4,5,6,7,8,11,12,15,16,21,23,24,25,27,28,29,30,31','video' => '','calendar_type' => 'Always','booking_type' => NULL,'cancel_policy' => 'Flexible','popular' => 'No','started' => 'Yes','recommended' => 'Yes','views_count' => '0','status' => 'Listed','verified' => 'Approved','created_at' => '2017-08-14 11:18:03','updated_at' => '2017-08-14 12:07:56','deleted_at' => NULL, 'is_shared' => 'Yes'],
            ['id' => '10017','user_id' => '10004','name' => '','sub_name' => 'Shared room in London','summary' => '','check_in_time' => 'Flexible','check_out_time' => 'Flexible','booking_message' => '','property_type' => '3','room_type' => '3','accommodates' => '7','bedrooms' => NULL,'beds' => NULL,'bed_type' => NULL,'bathrooms' => NULL,'amenities' => NULL,'video' => '','calendar_type' => NULL,'booking_type' => NULL,'cancel_policy' => 'Flexible','popular' => 'No','started' => 'Yes','recommended' => 'No','views_count' => '0','status' => NULL,'verified' => 'Pending','created_at' => '2017-08-18 05:46:19','updated_at' => '2017-08-18 05:46:26','deleted_at' => NULL, 'is_shared' => 'Yes'],
            ['id' => '10018','user_id' => '10004','name' => '','sub_name' => 'Private room in Chennai','summary' => '','check_in_time' => 'Flexible','check_out_time' => 'Flexible','booking_message' => '','property_type' => '1','room_type' => '2','accommodates' => '7','bedrooms' => '4','beds' => '7','bed_type' => '1','bathrooms' => '5.0','amenities' => NULL,'video' => '','calendar_type' => NULL,'booking_type' => NULL,'cancel_policy' => 'Flexible','popular' => 'No','started' => 'Yes','recommended' => 'No','views_count' => '0','status' => NULL,'verified' => 'Pending','created_at' => '2017-08-18 14:47:14','updated_at' => '2017-08-18 14:49:35','deleted_at' => NULL, 'is_shared' => 'No']
        ]);

        DB::table('rooms_beds')->insert([
            ['id' => '1','space_id' => '10001','bed_id' => 1,'bed_room_no' => 1,'count' => 1],
            ['id' => '2','space_id' => '10002','bed_id' => 1,'bed_room_no' => 1,'count' => 1],
            ['id' => '3','space_id' => '10003','bed_id' => 1,'bed_room_no' => 1,'count' => 1],
            ['id' => '4','space_id' => '10004','bed_id' => 1,'bed_room_no' => 1,'count' => 1],
            ['id' => '5','space_id' => '10005','bed_id' => 1,'bed_room_no' => 1,'count' => 1],
            ['id' => '6','space_id' => '10006','bed_id' => 1,'bed_room_no' => 1,'count' => 1],
            ['id' => '7','space_id' => '10007','bed_id' => 1,'bed_room_no' => 1,'count' => 1],
            ['id' => '8','space_id' => '10008','bed_id' => 1,'bed_room_no' => 1,'count' => 1],
            ['id' => '9','space_id' => '10009','bed_id' => 1,'bed_room_no' => 1,'count' => 1],
            ['id' => '10','space_id' => '10010','bed_id' => 1,'bed_room_no' => 1,'count' => 1],
            ['id' => '11','space_id' => '10011','bed_id' => 1,'bed_room_no' => 1,'count' => 1],
            ['id' => '12','space_id' => '10012','bed_id' => 1,'bed_room_no' => 1,'count' => 1],
            ['id' => '13','space_id' => '10013','bed_id' => 1,'bed_room_no' => 1,'count' => 1],
            ['id' => '14','space_id' => '10014','bed_id' => 1,'bed_room_no' => 1,'count' => 1],
            ['id' => '15','space_id' => '10015','bed_id' => 1,'bed_room_no' => 1,'count' => 1],
            ['id' => '16','space_id' => '10016','bed_id' => 1,'bed_room_no' => 1,'count' => 1],
            ['id' => '17','space_id' => '10017','bed_id' => 1,'bed_room_no' => 1,'count' => 1],
            ['id' => '18','space_id' => '10018','bed_id' => 1,'bed_room_no' => 1,'count' => 1],
        ]);
    }
}


                
                
