<?php

use Illuminate\Database\Seeder;

class SpaceTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		DB::table('activities_price')->delete();
		DB::table('availability_times')->delete();
		DB::table('space_activities')->delete();
		DB::table('space_availability')->delete();
		DB::table('space_description')->delete();
		DB::table('space_location')->delete();
		DB::table('space_photos')->delete();
		DB::table('space_price')->delete();
		DB::table('space_steps_status')->delete();
        DB::table('space')->delete();

        DB::table('space')->insert([
			array('id' => '10001','user_id' => '10004','name' => 'Private Dining Room + Bar - Chinato','sub_name' => 'Event Space in ','summary' => 'We\'re a clandestine Private Dining Room in a beautiful loft space on plaza path Street, in New York. Equipped with a full kitchen, we can provide a full family-style dinner service, or, guests can bring their own chefs, food or drinks. We can accommodate up to 60 people for seated dinners or 100 for standing or cocktail parties.','space_type' => '9','number_of_rooms' => '0','number_of_restrooms' => '4','number_of_guests' => '100','floor_number' => NULL,'sq_ft' => '127','size_type' => 'sq_ft','guest_access' => '1,3,4','guest_access_other' => NULL,'amenities' => '3,4,5,8,17,19','services' => '1,2,8','services_extra' => NULL,'space_style' => '2,3,5','special_feature' => '1,2,5,8','space_rules' => '1,4,6','booking_type' => 'request_to_book','cancellation_policy' => 'Flexible','popular' => 'Yes','views_count' => '2','status' => 'Listed','admin_status' => 'Approved','created_at' => '2019-08-22 11:49:29','updated_at' => '2019-10-19 18:34:45'),
			array('id' => '10002','user_id' => '10004','name' => 'Rustic 19th Century Venue With Room','sub_name' => 'Garden in ','summary' => 'Warm and welcoming venue perfect for those special days with family and friends. Events take place in the private courtyard on our open-air deck which features a retractable roof, moveable glass walls, and heating allowing you to make the most of the great outdoors in the colder seasons of the year. With seating for up to 90 guests our Patio is perfect for photoshoots, video interviews, intimate celebrations, birthdays, baby showers and bridal showers.','space_type' => '11','number_of_rooms' => '0','number_of_restrooms' => NULL,'number_of_guests' => '127','floor_number' => NULL,'sq_ft' => '100','size_type' => 'sq_ft','guest_access' => '2,4','guest_access_other' => NULL,'amenities' => '1,3,4,7','services' => '1,2,6','services_extra' => NULL,'space_style' => '','special_feature' => '','space_rules' => '2,3,6','booking_type' => 'instant_book','cancellation_policy' => 'Flexible','popular' => 'No','views_count' => '0','status' => 'Pending','admin_status' => 'Pending','created_at' => '2019-08-22 12:42:08','updated_at' => '2019-10-19 12:01:28'),
			array('id' => '10003','user_id' => '10004','name' => 'the \'GREENPOINTER\' Brooklyn Brownst','sub_name' => 'Commercial Kitchen in ','summary' => 'This three story Brooklyn towhome is a collection of three dreamy floors, each creating it\'s own unique vibe and setting. From exposed brick walls and wood beams to an oversized glass garage door opening up to the large backyard, this space is an over the top yet charming take on a lofty Brooklyn home.','space_type' => '8','number_of_rooms' => '4','number_of_restrooms' => '2','number_of_guests' => '50','floor_number' => NULL,'sq_ft' => '50','size_type' => 'sq_ft','guest_access' => '1,2,3','guest_access_other' => NULL,'amenities' => '1,6,10','services' => '6,8','services_extra' => NULL,'space_style' => '1,3','special_feature' => '2,5','space_rules' => '4,5,6','booking_type' => 'request_to_book','cancellation_policy' => 'Flexible','popular' => 'No','views_count' => '2','status' => 'Resubmit','admin_status' => 'Resubmit','created_at' => '2019-08-22 13:07:18','updated_at' => '2019-10-19 12:45:45'),
			array('id' => '10004','user_id' => '10004','name' => 'STUDIO B - Cyclorama Loft studio 30','sub_name' => 'Commercial Kitchen in ','summary' => 'We offer a 3000 sqf multivalent open space with a post-industrial feel and touch, perfect for photo and film shoots, organizing presentations, auditions and networking events.','space_type' => '8','number_of_rooms' => '4','number_of_restrooms' => '2','number_of_guests' => '50','floor_number' => NULL,'sq_ft' => '50','size_type' => 'sq_ft','guest_access' => '1,2,3','guest_access_other' => NULL,'amenities' => '1,6,10','services' => '6,8','services_extra' => NULL,'space_style' => '1,3','special_feature' => '2,5','space_rules' => '4,5,6','booking_type' => 'instant_book','cancellation_policy' => 'Flexible','popular' => 'Yes','views_count' => '8','status' => 'Listed','admin_status' => 'Approved','created_at' => '2019-08-22 13:07:18','updated_at' => '2019-10-21 14:50:11'),
			array('id' => '10005','user_id' => '10004','name' => 'Mid-Century Glass House','sub_name' => 'Commercial Kitchen in ','summary' => 'Inspired by the glass houses of Philip Johnson and Mies van der Rohe, this airy, light-filled home features a 42-foot living/dining room, two bedrooms, an office/study, a library with natural stone floor, a modern kitchen and two modern bathrooms. Every room in the home features at least one full wall of floor-to-ceiling glass.','space_type' => '8','number_of_rooms' => '4','number_of_restrooms' => '2','number_of_guests' => '50','floor_number' => NULL,'sq_ft' => '50','size_type' => 'sq_ft','guest_access' => '1,2,3','guest_access_other' => NULL,'amenities' => '1,6,10','services' => '6,8','services_extra' => NULL,'space_style' => '1,3','special_feature' => '2,5','space_rules' => '4,5,6','booking_type' => 'instant_book','cancellation_policy' => 'Flexible','popular' => 'No','views_count' => '2','status' => 'Listed','admin_status' => 'Approved','created_at' => '2019-08-22 13:07:18','updated_at' => '2019-10-19 16:51:00'),
			array('id' => '10006','user_id' => '10004','name' => 'Penthouse duplex two terraces','sub_name' => 'Commercial Kitchen in ','summary' => 'Our spaces are managed by some of NYC\'s most experienced and diversely-skilled group of professionals. Together, our team has a combined 10+ years of experience in production and event management, booking management, and organizing high profile meetings, workshops, and product launches in the luxury retail, art, technology, design and architecture industries.','space_type' => '8','number_of_rooms' => '4','number_of_restrooms' => '2','number_of_guests' => '50','floor_number' => NULL,'sq_ft' => '50','size_type' => 'sq_ft','guest_access' => '1,2,3','guest_access_other' => NULL,'amenities' => '1,6,10','services' => '6,8','services_extra' => NULL,'space_style' => '1,3','special_feature' => '2,5','space_rules' => '4,5,6','booking_type' => 'request_to_book','cancellation_policy' => 'Flexible','popular' => 'No','views_count' => '2','status' => 'Listed','admin_status' => 'Approved','created_at' => '2019-08-22 13:07:18','updated_at' => '2019-10-19 17:26:34'),
			array('id' => '10007','user_id' => '10002','name' => 'Lush Creative Midtown Studio','sub_name' => 'Auditorium in ','summary' => 'This creative studio is a uniquely lush touchdown space in the heart of Midtown. Home to designers, editors, audio engineers, casting directors, photographers, illustrators, and animators, we invite you to plug in and enjoy the green, creative ambiance of our space. Perfect for meetings, presentations, seminars, digital editing, photo shoots, and Parties. The location is no more than a five minute walk from Times Square, Bryant Park, Penn Station, Herald Square, and Grand Central.','space_type' => '4','number_of_rooms' => '3','number_of_restrooms' => '2','number_of_guests' => '25','floor_number' => '10','sq_ft' => '1500','size_type' => 'sq_ft','guest_access' => '1,3,4,5','guest_access_other' => NULL,'amenities' => '1,2,3,4,5,6,7,8,12,1','services' => '2,3,9','services_extra' => NULL,'space_style' => '4,5','special_feature' => '1,2,7,8,11,12','space_rules' => '1,2,3','booking_type' => 'request_to_book','cancellation_policy' => 'Flexible','popular' => 'No','views_count' => '6','status' => 'Listed','admin_status' => 'Approved','created_at' => '2019-10-18 16:09:51','updated_at' => '2019-10-21 13:00:25'),
			array('id' => '10008','user_id' => '10001','name' => 'Multi-Use Event/Gallery/ Cafe Space','sub_name' => 'Event Space in ','summary' => 'We offer this location for private parties, corporate mixers, birthday celebrations, cocktail receptions, seminars, concerts, fund-raisers, and company holiday parties. It is also available to rent for your own weekly classes and/or workshops. It is located on the ground floor.','space_type' => '9','number_of_rooms' => '2','number_of_restrooms' => '5','number_of_guests' => '40','floor_number' => '0','sq_ft' => '700','size_type' => 'sq_ft','guest_access' => '1,2,4','guest_access_other' => NULL,'amenities' => '4,5,6,7,8,22,23','services' => '1,3,9','services_extra' => '','space_style' => '1,4,5','special_feature' => '1,2,4','space_rules' => '1,2','booking_type' => 'request_to_book','cancellation_policy' => 'Flexible','popular' => 'Yes','views_count' => '2','status' => 'Listed','admin_status' => 'Approved','created_at' => '2019-10-18 16:11:30','updated_at' => '2019-10-19 15:46:25'),
			array('id' => '10009','user_id' => '10002','name' => 'Fully Equipped Spacious SoHo Photo','sub_name' => 'Photo Studio in ','summary' => 'This newly built studio is located in the heart of SoHo, Manhattan just steps from the Broadway/Lafayette and Prince Street subway stops. With over 1000 sq ft of studio space, it functions perfectly for both photography and video productions. It features a hair and makeup station, lounge area, private bathroom, digital workstation (iMac pro) and private studio entrance.','space_type' => '2','number_of_rooms' => '0','number_of_restrooms' => NULL,'number_of_guests' => '35','floor_number' => '7','sq_ft' => '1000','size_type' => 'sq_ft','guest_access' => '1,3,4,5','guest_access_other' => NULL,'amenities' => '2,3,4,5,7,8,14,16,17','services' => '2,6,8,9','services_extra' => NULL,'space_style' => '1,6,7','special_feature' => '5,8,11','space_rules' => '3','booking_type' => 'instant_book','cancellation_policy' => 'Moderate','popular' => 'No','views_count' => '4','status' => 'Listed','admin_status' => 'Approved','created_at' => '2019-10-18 16:38:55','updated_at' => '2019-10-19 15:46:17'),
			array('id' => '10010','user_id' => '10001','name' => 'NYC Views - photo, meeting, event.','sub_name' => 'Photo Studio in New York','summary' => 'Perfect for your next NYC photo shoot, video shoot, promo video, film, small event, or meeting, this luxurious studio is above the clouds in New York City. Experience breathtaking panoramic views on the 64th floor, facing east, south, and west. Influencers, film, photography, and media companies are showcasing their brand on top of the most magnificent city in the world. 12-foot ceilings with natural light pouring in the room make the space perfect for a photo shoot, film project.','space_type' => '2','number_of_rooms' => '2','number_of_restrooms' => '3','number_of_guests' => '10','floor_number' => '64','sq_ft' => '800','size_type' => 'sq_ft','guest_access' => '1,3,4','guest_access_other' => NULL,'amenities' => '4,5,7,8,16,22,23,24','services' => '1,2,3,4,8','services_extra' => '','space_style' => '4,5','special_feature' => '2,5,8,12','space_rules' => '1,2','booking_type' => 'request_to_book','cancellation_policy' => 'Flexible','popular' => 'No','views_count' => '1','status' => 'Listed','admin_status' => 'Approved','created_at' => '2019-10-18 16:45:11','updated_at' => '2019-10-19 17:31:56'),
			array('id' => '10011','user_id' => '10001','name' => 'Flatiron loft and beautiful kitchen','sub_name' => 'Commercial Loft in Budapest','summary' => 'Our original premier event space, is perfect for film and photo shoots, corporate and culinary events, private parties and elegant weddings. With over 10 years of experience we can provide a perfect venue for any event you can imagine, including fashion shows, product launches and celebrity chef demonstrations. Contact us anytime to set up an appointment to see our stunning spaces.','space_type' => '3','number_of_rooms' => '6','number_of_restrooms' => '3','number_of_guests' => '175','floor_number' => '7','sq_ft' => '4000','size_type' => 'sq_ft','guest_access' => '1,3,4','guest_access_other' => NULL,'amenities' => '2,4,5,6,7,8,22,23,24','services' => '2,3,8','services_extra' => '','space_style' => '5','special_feature' => '2,5,7,8,9','space_rules' => '1,2','booking_type' => 'instant_book','cancellation_policy' => 'Flexible','popular' => 'No','views_count' => '21','status' => 'Listed','admin_status' => 'Approved','created_at' => '2019-10-18 17:35:55','updated_at' => '2019-10-21 12:42:37'),
			array('id' => '10012','user_id' => '10001','name' => 'Conference on Western Bank of River','sub_name' => 'Banquet Hall in ','summary' => 'This 744 sqft well-appointed meeting space features high-end amenities, sits 40 comfortably but has a maximum capacity of 45 people, and can be set up in several different configurations to suit the needs of your group. Our modern conference center is the perfect place for your next meeting. Located in a Class A office building situated on the western bank of the Chicago River, our this space boasts large east-facing windows with beautiful views of the Chicago River.','space_type' => '5','number_of_rooms' => '5','number_of_restrooms' => '3','number_of_guests' => '45','floor_number' => '8','sq_ft' => '744','size_type' => 'sq_ft','guest_access' => '1,3,4,5','guest_access_other' => NULL,'amenities' => '4,6,7,8,16,17,18,22,','services' => '2,3,6','services_extra' => NULL,'space_style' => '1,2','special_feature' => '2,3,4,6,7,8','space_rules' => '1,2,6,7','booking_type' => 'instant_book','cancellation_policy' => 'Flexible','popular' => 'No','views_count' => '2','status' => 'Listed','admin_status' => 'Approved','created_at' => '2019-10-18 17:49:45','updated_at' => '2019-10-19 15:46:28'),
			array('id' => '10013','user_id' => '10003','name' => 'Photography,Video Production Studio','sub_name' => 'Photo Studio in ','summary' => 'Photography and Video Filming studio featuring a large 3 wall Cyc. Cyc wall is pre-lit with 11 Kino Flo 8 banks. Amenities include: Hair, Makeup and Wardrobe room, Restrooms with Shower, Loading dock door, separate entrance to Kitchen, lounge and private fenced property with a gate. Plenty of on-site gated parking and free street parking available.','space_type' => '2','number_of_rooms' => '5','number_of_restrooms' => '3','number_of_guests' => '150','floor_number' => '5','sq_ft' => '4200','size_type' => 'sq_ft','guest_access' => '1,3,4','guest_access_other' => NULL,'amenities' => '4,7,8,22,23,25,26,28','services' => '2,3,6','services_extra' => NULL,'space_style' => '2,4,5','special_feature' => '1,2,3,8','space_rules' => '1,2,6','booking_type' => 'instant_book','cancellation_policy' => 'Flexible','popular' => 'No','views_count' => '9','status' => 'Listed','admin_status' => 'Approved','created_at' => '2019-10-18 18:18:02','updated_at' => '2019-10-21 12:55:21'),
			array('id' => '10014','user_id' => '10003','name' => 'Amazing Modern Space For Any Event','sub_name' => 'Event Space in ','summary' => 'Need to host an event or office party. Any time of year this is the perfect atmosphere for the occasion. Cocktail are with seperate party room. Amazing modern A+ space with custom shelving and color changing LED lightning, huge modern reception area with LED lightning, speaker intercom system and Wi-Fi included. Private and gated parking for convenience and safety. Must see!','space_type' => '9','number_of_rooms' => '5','number_of_restrooms' => '4','number_of_guests' => '250','floor_number' => '7','sq_ft' => '4500','size_type' => 'sq_ft','guest_access' => '2,3,4','guest_access_other' => NULL,'amenities' => '4,5,6,7,8,11,12','services' => '2,3,4','services_extra' => NULL,'space_style' => '1,2,4','special_feature' => '2,3,6,7,8','space_rules' => '1,2,6','booking_type' => 'request_to_book','cancellation_policy' => 'Flexible','popular' => 'No','views_count' => '1','status' => 'Listed','admin_status' => 'Approved','created_at' => '2019-10-18 18:27:37','updated_at' => '2019-10-19 17:31:49'),
			array('id' => '10015','user_id' => '10003','name' => 'Outdoor pool deck for shoots/events','sub_name' => 'Event Space in ','summary' => 'The back yard, pool & deck are perfect for photo shoots or outdoor events .  It is a beautiful, clean space for photo shoots, commercial filming and more! Great open area, wifi, TV, sound system, and 20 available chairs for use','space_type' => '9','number_of_rooms' => '4','number_of_restrooms' => '2','number_of_guests' => '20','floor_number' => '5','sq_ft' => '20000','size_type' => 'sq_ft','guest_access' => '1,4','guest_access_other' => NULL,'amenities' => '4,5,6,11,13,17,23,24','services' => '2,3,4,6,8','services_extra' => NULL,'space_style' => '4,5','special_feature' => '2,4,5,8,9,10','space_rules' => '1,2','booking_type' => 'request_to_book','cancellation_policy' => 'Flexible','popular' => 'Yes','views_count' => '1','status' => 'Listed','admin_status' => 'Approved','created_at' => '2019-10-18 18:48:37','updated_at' => '2019-10-19 12:48:45'),
			array('id' => '10016','user_id' => '10003','name' => 'Unique Gallery & Event Space !','sub_name' => 'Gallery in ','summary' => 'Welcome to our studio! From Corporate & Special Events to Social & Private and Pop Ups, we will be sure to meet all you event space and event production needs. We offer : over 5000 square feet indoor/outdoor space which include Front Entrance, Roll up Garage Door, Front Foyer area, Gallery, Main event room, Stage, Back Stage area, Basic sound system, Basic lighting, Back Foyer area','space_type' => '10','number_of_rooms' => '4','number_of_restrooms' => '3','number_of_guests' => '50','floor_number' => '4','sq_ft' => '5000','size_type' => 'sq_ft','guest_access' => '1,2,3,4','guest_access_other' => NULL,'amenities' => '2,4,5,6,7,8,11,13,26','services' => '2,3,8','services_extra' => NULL,'space_style' => '4,5','special_feature' => '2,3,6,7,8,9','space_rules' => '2,3,4','booking_type' => 'request_to_book','cancellation_policy' => 'Flexible','popular' => 'No','views_count' => '2','status' => 'Listed','admin_status' => 'Approved','created_at' => '2019-10-18 19:04:48','updated_at' => '2019-10-19 17:30:29'),
			array('id' => '10017','user_id' => '10002','name' => 'Industrial Dance Studio','sub_name' => 'Event Space in ','summary' => 'This space is an ideal dance, yoga, and fitness studio. It can be used for meetings, photography and film. Great party venue. 34ft full length mirrors. It’s a rectangle shaped room with plenty of natural light. It’s wide open allowing you to use it for anything activities. Sound system is included. Water fountain included.','space_type' => '9','number_of_rooms' => '5','number_of_restrooms' => '3','number_of_guests' => '50','floor_number' => '2','sq_ft' => '840','size_type' => 'sq_ft','guest_access' => '1,2,5','guest_access_other' => NULL,'amenities' => '1,2,3,4,6,7,8,9,10,1','services' => '1,2,3,4,5,6','services_extra' => '','space_style' => '2,5','special_feature' => '2,5,8,9','space_rules' => '1,4,5','booking_type' => 'request_to_book','cancellation_policy' => 'Flexible','popular' => 'Yes','views_count' => '7','status' => 'Listed','admin_status' => 'Approved','created_at' => '2019-10-18 19:31:51','updated_at' => '2019-10-19 17:29:00'),
			array('id' => '10018','user_id' => '10002','name' => 'Versatile Outdoor Venue Space','sub_name' => 'Outdoor Space in ','summary' => 'We offer 2,500 sq. ft. of outdoor space fit to accommodate an endless range of purposes. Perfect for art exhibitions, launch parties, photo/TV and commercial shoots, trunk shows, day and night events, we provide the ideal venue for any event or gathering. Just beyond the walls, a 30,000 sq. ft. creative studio space, it offers tons of space, polished woodwork, colorful murals, unique seating, garage entrance, and natural light. Can accommodate up to 135 guests comfortably.','space_type' => '15','number_of_rooms' => '0','number_of_restrooms' => '3','number_of_guests' => '135','floor_number' => NULL,'sq_ft' => '2500','size_type' => 'sq_ft','guest_access' => '4','guest_access_other' => NULL,'amenities' => '8,13,14,22,23,24,31','services' => '2,4,5,6,8,9','services_extra' => NULL,'space_style' => '6,7','special_feature' => '4,8','space_rules' => '6','booking_type' => 'instant_book','cancellation_policy' => 'Flexible','popular' => 'No','views_count' => '0','status' => 'Listed','admin_status' => 'Approved','created_at' => '2019-10-19 17:43:56','updated_at' => '2019-10-19 18:01:25'),
			array('id' => '10019','user_id' => '10006','name' => 'Lush Garden in Los Angeles','sub_name' => 'Garden in ','summary' => 'An enchanting event space set in an idyllic garden surrounded by citrus and avocado trees, sage and lemongrass, a hot tub, and a rustic vine-draped pergola. Ideal for bridal/baby showers, cocktail parties, receptions, birthdays, celebratory dinners, or any other intimate gathering, the 2,000 sq. ft. garden sits on a deep, quiet lot, centrally located in the Faircrest Heights neighborhood of LA.','space_type' => '11','number_of_rooms' => '0','number_of_restrooms' => '2','number_of_guests' => '250','floor_number' => NULL,'sq_ft' => '2500','size_type' => 'sq_ft','guest_access' => '1,4','guest_access_other' => NULL,'amenities' => '1,5,8,10,11,14,21,22','services' => '','services_extra' => NULL,'space_style' => '1,7','special_feature' => '4,8,9','space_rules' => '1,6','booking_type' => 'instant_book','cancellation_policy' => 'Flexible','popular' => 'No','views_count' => '2','status' => 'Listed','admin_status' => 'Approved','created_at' => '2019-10-21 16:06:02','updated_at' => '2019-10-22 10:49:26'),
        ]);

		DB::table('space_activities')->insert([
			array('id' => '1','space_id' => '10001','activity_type_id' => '1','activities' => '1','sub_activities' => '1'),
			array('id' => '2','space_id' => '10001','activity_type_id' => '6','activities' => '10','sub_activities' => ''),
			array('id' => '3','space_id' => '10002','activity_type_id' => '1','activities' => '9','sub_activities' => ''),
			array('id' => '4','space_id' => '10002','activity_type_id' => '3','activities' => '5','sub_activities' => ''),
			array('id' => '5','space_id' => '10002','activity_type_id' => '5','activities' => '6','sub_activities' => ''),
			array('id' => '6','space_id' => '10003','activity_type_id' => '1','activities' => '1,9','sub_activities' => '1,2,3,'),
			array('id' => '7','space_id' => '10006','activity_type_id' => '5','activities' => '6','sub_activities' => ''),
			array('id' => '8','space_id' => '10006','activity_type_id' => '6','activities' => '10','sub_activities' => ''),
			array('id' => '9','space_id' => '10006','activity_type_id' => '3','activities' => '5','sub_activities' => ''),
			array('id' => '10','space_id' => '10005','activity_type_id' => '2','activities' => '2','sub_activities' => '4,5'),
			array('id' => '11','space_id' => '10005','activity_type_id' => '3','activities' => '3','sub_activities' => '7'),
			array('id' => '12','space_id' => '10004','activity_type_id' => '1','activities' => '1','sub_activities' => '1,2'),
			array('id' => '13','space_id' => '10004','activity_type_id' => '3','activities' => '3','sub_activities' => '6,7,8'),
			array('id' => '14','space_id' => '10007','activity_type_id' => '3','activities' => '3,5','sub_activities' => '6,7,8,'),
			array('id' => '15','space_id' => '10007','activity_type_id' => '5','activities' => '6','sub_activities' => ''),
			array('id' => '16','space_id' => '10008','activity_type_id' => '1','activities' => '1,8,9','sub_activities' => '2,,'),
			array('id' => '17','space_id' => '10008','activity_type_id' => '2','activities' => '2','sub_activities' => '4,5'),
			array('id' => '18','space_id' => '10008','activity_type_id' => '3','activities' => '3','sub_activities' => '8'),
			array('id' => '19','space_id' => '10008','activity_type_id' => '4','activities' => '4','sub_activities' => ''),
			array('id' => '20','space_id' => '10008','activity_type_id' => '5','activities' => '6','sub_activities' => ''),
			array('id' => '21','space_id' => '10009','activity_type_id' => '3','activities' => '5','sub_activities' => ''),
			array('id' => '22','space_id' => '10010','activity_type_id' => '1','activities' => '1','sub_activities' => '2,3'),
			array('id' => '23','space_id' => '10010','activity_type_id' => '2','activities' => '2','sub_activities' => '4,5'),
			array('id' => '24','space_id' => '10010','activity_type_id' => '3','activities' => '3','sub_activities' => '6,7,8'),
			array('id' => '25','space_id' => '10010','activity_type_id' => '4','activities' => '4','sub_activities' => ''),
			array('id' => '26','space_id' => '10011','activity_type_id' => '1','activities' => '1','sub_activities' => '1,2,3'),
			array('id' => '27','space_id' => '10011','activity_type_id' => '2','activities' => '2','sub_activities' => '4,5'),
			array('id' => '28','space_id' => '10011','activity_type_id' => '3','activities' => '3,5','sub_activities' => '6,8,'),
			array('id' => '29','space_id' => '10011','activity_type_id' => '5','activities' => '6','sub_activities' => ''),
			array('id' => '30','space_id' => '10012','activity_type_id' => '1','activities' => '1','sub_activities' => '1,2,3'),
			array('id' => '31','space_id' => '10012','activity_type_id' => '2','activities' => '2','sub_activities' => '4,5'),
			array('id' => '32','space_id' => '10013','activity_type_id' => '1','activities' => '1,8,9','sub_activities' => '1,2,3,,'),
			array('id' => '33','space_id' => '10013','activity_type_id' => '3','activities' => '3,5','sub_activities' => '6,7,8,'),
			array('id' => '34','space_id' => '10013','activity_type_id' => '4','activities' => '4','sub_activities' => ''),
			array('id' => '35','space_id' => '10014','activity_type_id' => '1','activities' => '1,8,9','sub_activities' => '3,,'),
			array('id' => '36','space_id' => '10014','activity_type_id' => '2','activities' => '2','sub_activities' => '4,5'),
			array('id' => '37','space_id' => '10014','activity_type_id' => '3','activities' => '3','sub_activities' => '6,7,8'),
			array('id' => '38','space_id' => '10014','activity_type_id' => '4','activities' => '4,11','sub_activities' => ','),
			array('id' => '39','space_id' => '10014','activity_type_id' => '5','activities' => '6','sub_activities' => ''),
			array('id' => '40','space_id' => '10014','activity_type_id' => '6','activities' => '10','sub_activities' => ''),
			array('id' => '41','space_id' => '10015','activity_type_id' => '1','activities' => '7,8,9','sub_activities' => ',,'),
			array('id' => '42','space_id' => '10015','activity_type_id' => '3','activities' => '3','sub_activities' => '6,7,8'),
			array('id' => '43','space_id' => '10015','activity_type_id' => '4','activities' => '4','sub_activities' => ''),
			array('id' => '44','space_id' => '10015','activity_type_id' => '5','activities' => '6','sub_activities' => ''),
			array('id' => '45','space_id' => '10016','activity_type_id' => '1','activities' => '1','sub_activities' => '1,2,3'),
			array('id' => '46','space_id' => '10016','activity_type_id' => '3','activities' => '3','sub_activities' => '6,7,8'),
			array('id' => '47','space_id' => '10016','activity_type_id' => '5','activities' => '6','sub_activities' => ''),
			array('id' => '48','space_id' => '10016','activity_type_id' => '6','activities' => '10','sub_activities' => ''),
			array('id' => '49','space_id' => '10017','activity_type_id' => '1','activities' => '1','sub_activities' => '1,2,3'),
			array('id' => '50','space_id' => '10017','activity_type_id' => '3','activities' => '3,5','sub_activities' => '8,'),
			array('id' => '51','space_id' => '10018','activity_type_id' => '1','activities' => '9','sub_activities' => ''),
			array('id' => '52','space_id' => '10018','activity_type_id' => '2','activities' => '12','sub_activities' => ''),
			array('id' => '53','space_id' => '10018','activity_type_id' => '5','activities' => '6','sub_activities' => ''),
			array('id' => '54','space_id' => '10018','activity_type_id' => '6','activities' => '10','sub_activities' => ''),
			array('id' => '55','space_id' => '10019','activity_type_id' => '3','activities' => '3','sub_activities' => '8'),
  			array('id' => '56','space_id' => '10019','activity_type_id' => '5','activities' => '6','sub_activities' => '')
        ]);

        DB::table('space_availability')->insert([
			array('id' => '1','space_id' => '10001','day' => '0','status' => 'All'),
			array('id' => '2','space_id' => '10001','day' => '1','status' => 'Open'),
			array('id' => '3','space_id' => '10001','day' => '2','status' => 'All'),
			array('id' => '4','space_id' => '10001','day' => '3','status' => 'All'),
			array('id' => '5','space_id' => '10001','day' => '4','status' => 'All'),
			array('id' => '6','space_id' => '10001','day' => '5','status' => 'All'),
			array('id' => '7','space_id' => '10001','day' => '6','status' => 'All'),
			array('id' => '8','space_id' => '10002','day' => '0','status' => 'All'),
			array('id' => '9','space_id' => '10002','day' => '1','status' => 'Open'),
			array('id' => '10','space_id' => '10002','day' => '2','status' => 'All'),
			array('id' => '11','space_id' => '10002','day' => '3','status' => 'Closed'),
			array('id' => '12','space_id' => '10002','day' => '4','status' => 'Closed'),
			array('id' => '13','space_id' => '10002','day' => '5','status' => 'Closed'),
			array('id' => '14','space_id' => '10002','day' => '6','status' => 'Closed'),
			array('id' => '15','space_id' => '10003','day' => '0','status' => 'All'),
			array('id' => '16','space_id' => '10003','day' => '1','status' => 'All'),
			array('id' => '17','space_id' => '10003','day' => '2','status' => 'All'),
			array('id' => '18','space_id' => '10003','day' => '3','status' => 'All'),
			array('id' => '19','space_id' => '10003','day' => '4','status' => 'All'),
			array('id' => '20','space_id' => '10003','day' => '5','status' => 'All'),
			array('id' => '21','space_id' => '10003','day' => '6','status' => 'All'),
			array('id' => '22','space_id' => '10004','day' => '0','status' => 'All'),
			array('id' => '23','space_id' => '10004','day' => '1','status' => 'All'),
			array('id' => '24','space_id' => '10004','day' => '2','status' => 'All'),
			array('id' => '25','space_id' => '10004','day' => '3','status' => 'All'),
			array('id' => '26','space_id' => '10004','day' => '4','status' => 'All'),
			array('id' => '27','space_id' => '10004','day' => '5','status' => 'All'),
			array('id' => '28','space_id' => '10004','day' => '6','status' => 'All'),
			array('id' => '29','space_id' => '10005','day' => '0','status' => 'All'),
			array('id' => '30','space_id' => '10005','day' => '1','status' => 'All'),
			array('id' => '31','space_id' => '10005','day' => '2','status' => 'All'),
			array('id' => '32','space_id' => '10005','day' => '3','status' => 'All'),
			array('id' => '33','space_id' => '10005','day' => '4','status' => 'All'),
			array('id' => '34','space_id' => '10005','day' => '5','status' => 'Closed'),
			array('id' => '35','space_id' => '10005','day' => '6','status' => 'Closed'),
			array('id' => '36','space_id' => '10006','day' => '0','status' => 'All'),
			array('id' => '37','space_id' => '10006','day' => '1','status' => 'All'),
			array('id' => '38','space_id' => '10006','day' => '2','status' => 'All'),
			array('id' => '39','space_id' => '10006','day' => '3','status' => 'All'),
			array('id' => '40','space_id' => '10006','day' => '4','status' => 'All'),
			array('id' => '41','space_id' => '10006','day' => '5','status' => 'Closed'),
			array('id' => '42','space_id' => '10006','day' => '6','status' => 'Closed'),
			array('id' => '43','space_id' => '10007','day' => '0','status' => 'All'),
			array('id' => '44','space_id' => '10007','day' => '1','status' => 'All'),
			array('id' => '45','space_id' => '10007','day' => '2','status' => 'All'),
			array('id' => '46','space_id' => '10007','day' => '3','status' => 'All'),
			array('id' => '47','space_id' => '10007','day' => '4','status' => 'All'),
			array('id' => '48','space_id' => '10007','day' => '5','status' => 'All'),
			array('id' => '49','space_id' => '10007','day' => '6','status' => 'All'),
			array('id' => '50','space_id' => '10008','day' => '0','status' => 'All'),
			array('id' => '51','space_id' => '10008','day' => '1','status' => 'All'),
			array('id' => '52','space_id' => '10008','day' => '2','status' => 'All'),
			array('id' => '53','space_id' => '10008','day' => '3','status' => 'All'),
			array('id' => '54','space_id' => '10008','day' => '4','status' => 'All'),
			array('id' => '55','space_id' => '10008','day' => '5','status' => 'All'),
			array('id' => '56','space_id' => '10008','day' => '6','status' => 'All'),
			array('id' => '57','space_id' => '10009','day' => '0','status' => 'All'),
			array('id' => '58','space_id' => '10009','day' => '1','status' => 'Open'),
			array('id' => '59','space_id' => '10009','day' => '2','status' => 'All'),
			array('id' => '60','space_id' => '10009','day' => '3','status' => 'All'),
			array('id' => '61','space_id' => '10009','day' => '4','status' => 'All'),
			array('id' => '62','space_id' => '10009','day' => '5','status' => 'All'),
			array('id' => '63','space_id' => '10009','day' => '6','status' => 'All'),
			array('id' => '64','space_id' => '10010','day' => '0','status' => 'All'),
			array('id' => '65','space_id' => '10010','day' => '1','status' => 'All'),
			array('id' => '66','space_id' => '10010','day' => '2','status' => 'All'),
			array('id' => '67','space_id' => '10010','day' => '3','status' => 'All'),
			array('id' => '68','space_id' => '10010','day' => '4','status' => 'All'),
			array('id' => '69','space_id' => '10010','day' => '5','status' => 'All'),
			array('id' => '70','space_id' => '10010','day' => '6','status' => 'All'),
			array('id' => '71','space_id' => '10011','day' => '0','status' => 'All'),
			array('id' => '72','space_id' => '10011','day' => '1','status' => 'All'),
			array('id' => '73','space_id' => '10011','day' => '2','status' => 'All'),
			array('id' => '74','space_id' => '10011','day' => '3','status' => 'All'),
			array('id' => '75','space_id' => '10011','day' => '4','status' => 'All'),
			array('id' => '76','space_id' => '10011','day' => '5','status' => 'All'),
			array('id' => '77','space_id' => '10011','day' => '6','status' => 'All'),
			array('id' => '78','space_id' => '10012','day' => '0','status' => 'All'),
			array('id' => '79','space_id' => '10012','day' => '1','status' => 'All'),
			array('id' => '80','space_id' => '10012','day' => '2','status' => 'All'),
			array('id' => '81','space_id' => '10012','day' => '3','status' => 'All'),
			array('id' => '82','space_id' => '10012','day' => '4','status' => 'All'),
			array('id' => '83','space_id' => '10012','day' => '5','status' => 'All'),
			array('id' => '84','space_id' => '10012','day' => '6','status' => 'All'),
			array('id' => '85','space_id' => '10013','day' => '0','status' => 'All'),
			array('id' => '86','space_id' => '10013','day' => '1','status' => 'All'),
			array('id' => '87','space_id' => '10013','day' => '2','status' => 'All'),
			array('id' => '88','space_id' => '10013','day' => '3','status' => 'All'),
			array('id' => '89','space_id' => '10013','day' => '4','status' => 'All'),
			array('id' => '90','space_id' => '10013','day' => '5','status' => 'All'),
			array('id' => '91','space_id' => '10013','day' => '6','status' => 'All'),
			array('id' => '92','space_id' => '10014','day' => '0','status' => 'All'),
			array('id' => '93','space_id' => '10014','day' => '1','status' => 'All'),
			array('id' => '94','space_id' => '10014','day' => '2','status' => 'All'),
			array('id' => '95','space_id' => '10014','day' => '3','status' => 'All'),
			array('id' => '96','space_id' => '10014','day' => '4','status' => 'All'),
			array('id' => '97','space_id' => '10014','day' => '5','status' => 'All'),
			array('id' => '98','space_id' => '10014','day' => '6','status' => 'All'),
			array('id' => '99','space_id' => '10015','day' => '0','status' => 'All'),
			array('id' => '100','space_id' => '10015','day' => '1','status' => 'All'),
			array('id' => '101','space_id' => '10015','day' => '2','status' => 'All'),
			array('id' => '102','space_id' => '10015','day' => '3','status' => 'All'),
			array('id' => '103','space_id' => '10015','day' => '4','status' => 'All'),
			array('id' => '104','space_id' => '10015','day' => '5','status' => 'All'),
			array('id' => '105','space_id' => '10015','day' => '6','status' => 'All'),
			array('id' => '106','space_id' => '10016','day' => '0','status' => 'All'),
			array('id' => '107','space_id' => '10016','day' => '1','status' => 'All'),
			array('id' => '108','space_id' => '10016','day' => '2','status' => 'All'),
			array('id' => '109','space_id' => '10016','day' => '3','status' => 'All'),
			array('id' => '110','space_id' => '10016','day' => '4','status' => 'All'),
			array('id' => '111','space_id' => '10016','day' => '5','status' => 'All'),
			array('id' => '112','space_id' => '10016','day' => '6','status' => 'All'),
			array('id' => '113','space_id' => '10017','day' => '0','status' => 'All'),
			array('id' => '114','space_id' => '10017','day' => '1','status' => 'All'),
			array('id' => '115','space_id' => '10017','day' => '2','status' => 'All'),
			array('id' => '116','space_id' => '10017','day' => '3','status' => 'All'),
			array('id' => '117','space_id' => '10017','day' => '4','status' => 'All'),
			array('id' => '118','space_id' => '10017','day' => '5','status' => 'All'),
			array('id' => '119','space_id' => '10017','day' => '6','status' => 'All'),
			array('id' => '120','space_id' => '10018','day' => '0','status' => 'All'),
			array('id' => '121','space_id' => '10018','day' => '1','status' => 'All'),
			array('id' => '122','space_id' => '10018','day' => '2','status' => 'All'),
			array('id' => '123','space_id' => '10018','day' => '3','status' => 'All'),
			array('id' => '124','space_id' => '10018','day' => '4','status' => 'All'),
			array('id' => '125','space_id' => '10018','day' => '5','status' => 'All'),
			array('id' => '126','space_id' => '10018','day' => '6','status' => 'All'),
			array('id' => '127','space_id' => '10019','day' => '0','status' => 'All'),
			array('id' => '128','space_id' => '10019','day' => '1','status' => 'All'),
			array('id' => '129','space_id' => '10019','day' => '2','status' => 'All'),
			array('id' => '130','space_id' => '10019','day' => '3','status' => 'All'),
			array('id' => '131','space_id' => '10019','day' => '4','status' => 'All'),
			array('id' => '132','space_id' => '10019','day' => '5','status' => 'All'),
			array('id' => '133','space_id' => '10019','day' => '6','status' => 'All'),
        ]);

        DB::table('space_description')->insert([
			array('space_id' => '10001','interaction' => '','notes' => '','neighborhood_overview' => '','transit' => ''),
			array('space_id' => '10002','interaction' => '','notes' => '','neighborhood_overview' => '','transit' => ''),
			array('space_id' => '10003','interaction' => '','notes' => '','neighborhood_overview' => '','transit' => ''),
			array('space_id' => '10004','interaction' => '','notes' => '','neighborhood_overview' => '','transit' => ''),
			array('space_id' => '10005','interaction' => '','notes' => '','neighborhood_overview' => '','transit' => ''),
			array('space_id' => '10006','interaction' => '','notes' => '','neighborhood_overview' => '','transit' => ''),
			array('space_id' => '10007','interaction' => '','notes' => '','neighborhood_overview' => '','transit' => ''),
			array('space_id' => '10008','interaction' => '','notes' => '','neighborhood_overview' => '','transit' => ''),
			array('space_id' => '10009','interaction' => '','notes' => '','neighborhood_overview' => '','transit' => ''),
			array('space_id' => '10010','interaction' => '','notes' => '','neighborhood_overview' => '','transit' => ''),
			array('space_id' => '10011','interaction' => '','notes' => '','neighborhood_overview' => '','transit' => ''),
			array('space_id' => '10012','interaction' => '','notes' => '','neighborhood_overview' => '','transit' => ''),
			array('space_id' => '10013','interaction' => '','notes' => '','neighborhood_overview' => '','transit' => ''),
			array('space_id' => '10014','interaction' => '','notes' => '','neighborhood_overview' => '','transit' => ''),
			array('space_id' => '10015','interaction' => '','notes' => '','neighborhood_overview' => '','transit' => ''),
			array('space_id' => '10016','interaction' => '','notes' => '','neighborhood_overview' => '','transit' => ''),
			array('space_id' => '10017','interaction' => '','notes' => '','neighborhood_overview' => '','transit' => ''),
			array('space_id' => '10018','interaction' => '','notes' => '','neighborhood_overview' => '','transit' => ''),
			array('space_id' => '10019','interaction' => '','notes' => '','neighborhood_overview' => '','transit' => ''),
        ]);

        DB::table('space_location')->insert([
			array('id' => '1','space_id' => '10001','address_line_1' => '1 Police Plaza Path','address_line_2' => '','city' => 'New York','state' => 'New York','country' => 'US','postal_code' => '10038','latitude' => '40.7120619','longitude' => '-74.0023853','guidance' => ''),
			array('id' => '2','space_id' => '10002','address_line_1' => '104-66 46th Avenue','address_line_2' => '','city' => '','state' => 'New York','country' => 'US','postal_code' => '11368','latitude' => '40.74689','longitude' => '-73.857384','guidance' => ''),
			array('id' => '3','space_id' => '10003','address_line_1' => '1525 M Street Northwest','address_line_2' => '','city' => 'Washington','state' => 'District of Columbia','country' => 'US','postal_code' => '20005','latitude' => '38.9059539','longitude' => '-77.0353015','guidance' => ''),
			array('id' => '4','space_id' => '10004','address_line_1' => '104-66 46th Avenue','address_line_2' => '','city' => 'Yorktown Heights','state' => 'New York','country' => 'US','postal_code' => '10598','latitude' => '41.2709274','longitude' => '-73.7776336','guidance' => ''),
			array('id' => '5','space_id' => '10005','address_line_1' => '2 Monroe Street','address_line_2' => '','city' => 'New York','state' => 'New York','country' => 'US','postal_code' => '100002','latitude' => '40.7109219','longitude' => '-73.995427','guidance' => ''),
			array('id' => '6','space_id' => '10006','address_line_1' => '193 Greenpoint Avenue','address_line_2' => '','city' => 'Washington','state' => 'New York','country' => 'US','postal_code' => '11222','latitude' => '40.7305906','longitude' => '-73.9518989','guidance' => ''),
			array('id' => '7','space_id' => '10007','address_line_1' => '','address_line_2' => '','city' => 'New York','state' => 'New York','country' => 'US','postal_code' => '','latitude' => '40.7550419','longitude' => '-73.984198','guidance' => ''),
			array('id' => '8','space_id' => '10008','address_line_1' => '32Z Quai de Grenelle','address_line_2' => '','city' => 'Paris','state' => 'Île-de-France','country' => 'FR','postal_code' => '75015','latitude' => '48.8521807','longitude' => '2.2853453','guidance' => ''),
			array('id' => '9','space_id' => '10009','address_line_1' => '459 Broadway','address_line_2' => '','city' => 'New York','state' => 'New York','country' => 'US','postal_code' => '10013','latitude' => '40.7208388','longitude' => '-74.0009504','guidance' => ''),
			array('id' => '10','space_id' => '10010','address_line_1' => '577 9th Avenue','address_line_2' => '','city' => 'New York','state' => 'New York','country' => 'US','postal_code' => '10036','latitude' => '40.758617','longitude' => '-73.992638','guidance' => ''),
			array('id' => '11','space_id' => '10011','address_line_1' => '8 Győri út','address_line_2' => '','city' => 'Budapest','state' => '','country' => 'HU','postal_code' => '1123','latitude' => '47.4920272','longitude' => '19.02703','guidance' => ''),
			array('id' => '12','space_id' => '10012','address_line_1' => '10 North Desplaines Street','address_line_2' => '','city' => 'Chicago','state' => 'Illinois','country' => 'US','postal_code' => '60661','latitude' => '41.8823512','longitude' => '-87.644351','guidance' => ''),
			array('id' => '13','space_id' => '10013','address_line_1' => '5000 Estate Enighed','address_line_2' => '','city' => 'Independence','state' => 'Kansas','country' => 'US','postal_code' => '67301','latitude' => '37.0910199','longitude' => '-95.7109427','guidance' => ''),
			array('id' => '14','space_id' => '10014','address_line_1' => '21 Carrer de Can Diviu','address_line_2' => '','city' => 'Sabadell','state' => 'Catalunya','country' => 'ES','postal_code' => '08205','latitude' => '41.51305','longitude' => '2.104','guidance' => ''),
			array('id' => '15','space_id' => '10015','address_line_1' => '5221 Craven Court','address_line_2' => '','city' => 'Bensalem','state' => 'Pennsylvania','country' => 'US','postal_code' => '19020','latitude' => '40.1235628','longitude' => '-74.9316025','guidance' => ''),
			array('id' => '16','space_id' => '10016','address_line_1' => '142 West 23rd Street','address_line_2' => '','city' => 'New York','state' => 'New York','country' => 'US','postal_code' => '10011','latitude' => '40.7433363','longitude' => '-73.9946416','guidance' => ''),
			array('id' => '17','space_id' => '10017','address_line_1' => '32Z Quai de Grenelle','address_line_2' => '','city' => 'Paris','state' => 'Île-de-France','country' => 'FR','postal_code' => '75015','latitude' => '48.8521807','longitude' => '2.2853453000000172','guidance' => ''),
			array('id' => '18','space_id' => '10018','address_line_1' => '204 Greenpoint Avenue','address_line_2' => '','city' => '','state' => 'New York','country' => 'US','postal_code' => '11222','latitude' => '40.7302621','longitude' => '-73.9520343','guidance' => ''),
			array('id' => '19','space_id' => '10019','address_line_1' => '1807 South Bronson Avenue','address_line_2' => '','city' => 'Los Angeles','state' => 'California','country' => 'US','postal_code' => '90019','latitude' => '34.0414355','longitude' => '-118.3292778','guidance' => ''),
        ]);

        DB::table('space_photos')->insert([
			array('id' => '1','space_id' => '10001','name' => '01566454926.jpg','highlights' => '','source' => 'Local','order_id' => '2'),
			array('id' => '4','space_id' => '10003','name' => '01566459460.webp','highlights' => '','source' => 'Local','order_id' => '1'),
			array('id' => '8','space_id' => '10007','name' => '01571395239.jpeg','highlights' => '','source' => 'Local','order_id' => '1'),
			array('id' => '9','space_id' => '10007','name' => '01571395257.jpeg','highlights' => '','source' => 'Local','order_id' => '2'),
			array('id' => '10','space_id' => '10007','name' => '11571395257.jpeg','highlights' => '','source' => 'Local','order_id' => '3'),
			array('id' => '11','space_id' => '10007','name' => '21571395257.jpeg','highlights' => '','source' => 'Local','order_id' => '4'),
			array('id' => '12','space_id' => '10007','name' => '31571395258.jpeg','highlights' => '','source' => 'Local','order_id' => '5'),
			array('id' => '15','space_id' => '10008','name' => '01571396456.jpg','highlights' => '','source' => 'Local','order_id' => '1'),
			array('id' => '16','space_id' => '10008','name' => '01571396505.jpg','highlights' => '','source' => 'Local','order_id' => '2'),
			array('id' => '17','space_id' => '10008','name' => '01571396576.jpg','highlights' => '','source' => 'Local','order_id' => '3'),
			array('id' => '18','space_id' => '10008','name' => '01571396589.jpg','highlights' => '','source' => 'Local','order_id' => '4'),
			array('id' => '19','space_id' => '10009','name' => '01571396960.jpeg','highlights' => '','source' => 'Local','order_id' => '2'),
			array('id' => '20','space_id' => '10009','name' => '11571396961.jpeg','highlights' => '','source' => 'Local','order_id' => '3'),
			array('id' => '21','space_id' => '10009','name' => '21571396961.jpeg','highlights' => '','source' => 'Local','order_id' => '4'),
			array('id' => '22','space_id' => '10009','name' => '31571396961.jpeg','highlights' => '','source' => 'Local','order_id' => '1'),
			array('id' => '23','space_id' => '10010','name' => '01571398277.jpg','highlights' => '','source' => 'Local','order_id' => '1'),
			array('id' => '24','space_id' => '10010','name' => '01571398287.jpg','highlights' => '','source' => 'Local','order_id' => '2'),
			array('id' => '25','space_id' => '10010','name' => '01571398303.jpg','highlights' => '','source' => 'Local','order_id' => '3'),
			array('id' => '26','space_id' => '10010','name' => '01571398311.jpg','highlights' => '','source' => 'Local','order_id' => '4'),
			array('id' => '27','space_id' => '10011','name' => '01571400429.jpg','highlights' => '','source' => 'Local','order_id' => '1'),
			array('id' => '28','space_id' => '10011','name' => '01571400442.jpg','highlights' => '','source' => 'Local','order_id' => '2'),
			array('id' => '29','space_id' => '10011','name' => '01571400452.jpg','highlights' => '','source' => 'Local','order_id' => '3'),
			array('id' => '30','space_id' => '10011','name' => '01571400460.jpg','highlights' => '','source' => 'Local','order_id' => '4'),
			array('id' => '31','space_id' => '10012','name' => '01571401484.jpg','highlights' => '','source' => 'Local','order_id' => '1'),
			array('id' => '32','space_id' => '10012','name' => '01571401503.jpg','highlights' => '','source' => 'Local','order_id' => '2'),
			array('id' => '33','space_id' => '10012','name' => '11571401506.jpg','highlights' => '','source' => 'Local','order_id' => '3'),
			array('id' => '34','space_id' => '10012','name' => '21571401509.jpg','highlights' => '','source' => 'Local','order_id' => '4'),
			array('id' => '35','space_id' => '10013','name' => '01571402921.jpg','highlights' => '','source' => 'Local','order_id' => '1'),
			array('id' => '36','space_id' => '10013','name' => '01571402933.jpg','highlights' => '','source' => 'Local','order_id' => '2'),
			array('id' => '37','space_id' => '10013','name' => '01571402944.jpg','highlights' => '','source' => 'Local','order_id' => '3'),
			array('id' => '38','space_id' => '10013','name' => '01571402956.jpg','highlights' => '','source' => 'Local','order_id' => '4'),
			array('id' => '39','space_id' => '10014','name' => '01571403801.jpg','highlights' => '','source' => 'Local','order_id' => '2'),
			array('id' => '40','space_id' => '10014','name' => '11571403806.jpg','highlights' => '','source' => 'Local','order_id' => '3'),
			array('id' => '41','space_id' => '10014','name' => '21571403813.jpg','highlights' => '','source' => 'Local','order_id' => '4'),
			array('id' => '42','space_id' => '10014','name' => '31571403815.jpg','highlights' => '','source' => 'Local','order_id' => '1'),
			array('id' => '43','space_id' => '10015','name' => '01571405052.jpg','highlights' => '','source' => 'Local','order_id' => '2'),
			array('id' => '44','space_id' => '10015','name' => '11571405056.jpg','highlights' => '','source' => 'Local','order_id' => '3'),
			array('id' => '45','space_id' => '10015','name' => '21571405058.jpg','highlights' => '','source' => 'Local','order_id' => '4'),
			array('id' => '46','space_id' => '10015','name' => '31571405062.jpg','highlights' => '','source' => 'Local','order_id' => '1'),
			array('id' => '47','space_id' => '10016','name' => '01571406186.jpg','highlights' => '','source' => 'Local','order_id' => '1'),
			array('id' => '48','space_id' => '10016','name' => '01571406281.jpg','highlights' => '','source' => 'Local','order_id' => '2'),
			array('id' => '49','space_id' => '10016','name' => '01571406380.jpg','highlights' => '','source' => 'Local','order_id' => '3'),
			array('id' => '51','space_id' => '10016','name' => '01571406450.jpg','highlights' => '','source' => 'Local','order_id' => '4'),
			array('id' => '52','space_id' => '10017','name' => '01571407311.jpg','highlights' => '','source' => 'Local','order_id' => '1'),
			array('id' => '53','space_id' => '10017','name' => '11571407312.jpg','highlights' => '','source' => 'Local','order_id' => '2'),
			array('id' => '54','space_id' => '10017','name' => '21571407313.jpg','highlights' => '','source' => 'Local','order_id' => '3'),
			array('id' => '55','space_id' => '10006','name' => '01571465374.jpg','highlights' => '','source' => 'Local','order_id' => '1'),
			array('id' => '56','space_id' => '10006','name' => '01571465418.jpg','highlights' => '','source' => 'Local','order_id' => '2'),
			array('id' => '61','space_id' => '10002','name' => '01571466685.jpg','highlights' => '','source' => 'Local','order_id' => '3'),
			array('id' => '62','space_id' => '10002','name' => '01571466704.jpg','highlights' => '','source' => 'Local','order_id' => '4'),
			array('id' => '63','space_id' => '10001','name' => '01571482239.jpeg','highlights' => '','source' => 'Local','order_id' => '3'),
			array('id' => '64','space_id' => '10001','name' => '01571482245.jpeg','highlights' => '','source' => 'Local','order_id' => '4'),
			array('id' => '65','space_id' => '10001','name' => '01571482374.jpeg','highlights' => '','source' => 'Local','order_id' => '5'),
			array('id' => '66','space_id' => '10001','name' => '01571482581.jpeg','highlights' => '','source' => 'Local','order_id' => '1'),
			array('id' => '67','space_id' => '10004','name' => '01571483318.jpeg','highlights' => '','source' => 'Local','order_id' => '2'),
			array('id' => '68','space_id' => '10004','name' => '11571483319.jpeg','highlights' => '','source' => 'Local','order_id' => '3'),
			array('id' => '69','space_id' => '10004','name' => '21571483319.jpeg','highlights' => '','source' => 'Local','order_id' => '4'),
			array('id' => '70','space_id' => '10004','name' => '31571483319.jpeg','highlights' => '','source' => 'Local','order_id' => '5'),
			array('id' => '71','space_id' => '10004','name' => '41571483320.jpeg','highlights' => '','source' => 'Local','order_id' => '1'),
			array('id' => '72','space_id' => '10005','name' => '01571483769.jpeg','highlights' => '','source' => 'Local','order_id' => '2'),
			array('id' => '73','space_id' => '10005','name' => '11571483770.jpeg','highlights' => '','source' => 'Local','order_id' => '3'),
			array('id' => '74','space_id' => '10005','name' => '21571483770.jpeg','highlights' => '','source' => 'Local','order_id' => '1'),
			array('id' => '75','space_id' => '10005','name' => '31571483770.jpeg','highlights' => '','source' => 'Local','order_id' => '4'),
			array('id' => '77','space_id' => '10005','name' => '01571483986.jpeg','highlights' => '','source' => 'Local','order_id' => '5'),
			array('id' => '78','space_id' => '10006','name' => '01571486152.jpeg','highlights' => '','source' => 'Local','order_id' => '3'),
			array('id' => '79','space_id' => '10006','name' => '11571486153.jpeg','highlights' => '','source' => 'Local','order_id' => '4'),
			array('id' => '81','space_id' => '10018','name' => '01571488224.jpeg','highlights' => '','source' => 'Local','order_id' => '2'),
			array('id' => '82','space_id' => '10018','name' => '11571488224.jpeg','highlights' => '','source' => 'Local','order_id' => '3'),
			array('id' => '83','space_id' => '10018','name' => '01571488243.jpeg','highlights' => '','source' => 'Local','order_id' => '1'),
			array('id' => '84','space_id' => '10018','name' => '11571488243.jpeg','highlights' => '','source' => 'Local','order_id' => '4'),
			array('id' => '85','space_id' => '10018','name' => '21571488244.jpeg','highlights' => '','source' => 'Local','order_id' => '5'),
			array('id' => '86','space_id' => '10019','name' => '01571654423.jpeg','highlights' => '','source' => 'Local','order_id' => '2'),
			array('id' => '87','space_id' => '10019','name' => '11571654423.jpeg','highlights' => '','source' => 'Local','order_id' => '3'),
			array('id' => '88','space_id' => '10019','name' => '21571654424.jpeg','highlights' => '','source' => 'Local','order_id' => '4'),
			array('id' => '89','space_id' => '10019','name' => '31571654424.jpeg','highlights' => '','source' => 'Local','order_id' => '1'),
        ]);

        DB::table('space_price')->insert([
			array('space_id' => '10001','security' => '500','currency_code' => 'USD'),
			array('space_id' => '10002','security' => '1500','currency_code' => 'USD'),
			array('space_id' => '10003','security' => '100','currency_code' => 'USD'),
			array('space_id' => '10004','security' => '350','currency_code' => 'USD'),
			array('space_id' => '10005','security' => '250','currency_code' => 'USD'),
			array('space_id' => '10006','security' => '200','currency_code' => 'USD'),
			array('space_id' => '10009','security' => '10','currency_code' => 'USD'),
			array('space_id' => '10017','security' => '0','currency_code' => 'USD'),
        ]);

        DB::table('space_steps_status')->insert([
			array('space_id' => '10001','basics' => '1','description' => '1','location' => '1','photos' => '1','pricing' => '1'),
			array('space_id' => '10002','basics' => '1','description' => '1','location' => '1','photos' => '1','pricing' => '1'),
			array('space_id' => '10003','basics' => '1','description' => '1','location' => '1','photos' => '1','pricing' => '1'),
			array('space_id' => '10004','basics' => '1','description' => '1','location' => '1','photos' => '1','pricing' => '1'),
			array('space_id' => '10005','basics' => '1','description' => '1','location' => '1','photos' => '1','pricing' => '1'),
			array('space_id' => '10006','basics' => '1','description' => '1','location' => '1','photos' => '1','pricing' => '1'),
			array('space_id' => '10007','basics' => '1','description' => '1','location' => '1','photos' => '1','pricing' => '1'),
			array('space_id' => '10008','basics' => '1','description' => '1','location' => '1','photos' => '1','pricing' => '1'),
			array('space_id' => '10009','basics' => '1','description' => '1','location' => '1','photos' => '1','pricing' => '1'),
			array('space_id' => '10010','basics' => '1','description' => '1','location' => '1','photos' => '1','pricing' => '1'),
			array('space_id' => '10011','basics' => '1','description' => '1','location' => '1','photos' => '1','pricing' => '1'),
			array('space_id' => '10012','basics' => '1','description' => '1','location' => '1','photos' => '1','pricing' => '1'),
			array('space_id' => '10013','basics' => '1','description' => '1','location' => '1','photos' => '1','pricing' => '1'),
			array('space_id' => '10014','basics' => '1','description' => '1','location' => '1','photos' => '1','pricing' => '1'),
			array('space_id' => '10015','basics' => '1','description' => '1','location' => '1','photos' => '1','pricing' => '1'),
			array('space_id' => '10016','basics' => '1','description' => '1','location' => '1','photos' => '1','pricing' => '1'),
			array('space_id' => '10017','basics' => '1','description' => '1','location' => '1','photos' => '1','pricing' => '1'),
			array('space_id' => '10018','basics' => '1','description' => '1','location' => '1','photos' => '1','pricing' => '1'),
			array('space_id' => '10019','basics' => '1','description' => '1','location' => '1','photos' => '1','pricing' => '1'),
        ]);


        DB::table('activities_price')->insert([
			array('id' => '1','space_id' => '10001','activity_id' => '1','currency_code' => 'USD','min_hours' => '2','hourly' => '120','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '2','space_id' => '10001','activity_id' => '2','currency_code' => 'USD','min_hours' => '1','hourly' => '200','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '3','space_id' => '10002','activity_id' => '3','currency_code' => 'USD','min_hours' => '2','hourly' => '50','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '4','space_id' => '10002','activity_id' => '4','currency_code' => 'USD','min_hours' => '4','hourly' => '200','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '5','space_id' => '10002','activity_id' => '5','currency_code' => 'USD','min_hours' => '3','hourly' => '150','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '6','space_id' => '10003','activity_id' => '6','currency_code' => 'USD','min_hours' => '3','hourly' => '80','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '7','space_id' => '10004','activity_id' => '12','currency_code' => 'USD','min_hours' => '4','hourly' => '20','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '8','space_id' => '10004','activity_id' => '13','currency_code' => 'USD','min_hours' => '1','hourly' => '30','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '9','space_id' => '10005','activity_id' => '10','currency_code' => 'USD','min_hours' => '1','hourly' => '150','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '10','space_id' => '10005','activity_id' => '11','currency_code' => 'USD','min_hours' => '1','hourly' => '200','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '11','space_id' => '10006','activity_id' => '7','currency_code' => 'USD','min_hours' => '1','hourly' => '50','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '12','space_id' => '10006','activity_id' => '8','currency_code' => 'USD','min_hours' => '1','hourly' => '80','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '13','space_id' => '10006','activity_id' => '9','currency_code' => 'USD','min_hours' => '3','hourly' => '50','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '14','space_id' => '10007','activity_id' => '14','currency_code' => 'USD','min_hours' => '1','hourly' => '125','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '15','space_id' => '10007','activity_id' => '15','currency_code' => 'USD','min_hours' => '1','hourly' => '125','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '16','space_id' => '10008','activity_id' => '16','currency_code' => 'USD','min_hours' => '1','hourly' => '120','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '17','space_id' => '10008','activity_id' => '17','currency_code' => 'USD','min_hours' => '1','hourly' => '120','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '18','space_id' => '10008','activity_id' => '18','currency_code' => 'USD','min_hours' => '1','hourly' => '120','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '19','space_id' => '10008','activity_id' => '19','currency_code' => 'USD','min_hours' => '1','hourly' => '120','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '20','space_id' => '10008','activity_id' => '20','currency_code' => 'USD','min_hours' => '1','hourly' => '120','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '21','space_id' => '10009','activity_id' => '21','currency_code' => 'USD','min_hours' => '1','hourly' => '90','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '22','space_id' => '10010','activity_id' => '22','currency_code' => 'USD','min_hours' => '1','hourly' => '150','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '23','space_id' => '10010','activity_id' => '23','currency_code' => 'USD','min_hours' => '1','hourly' => '150','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '24','space_id' => '10010','activity_id' => '24','currency_code' => 'USD','min_hours' => '1','hourly' => '150','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '25','space_id' => '10010','activity_id' => '25','currency_code' => 'USD','min_hours' => '1','hourly' => '150','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '26','space_id' => '10011','activity_id' => '26','currency_code' => 'USD','min_hours' => '1','hourly' => '450','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '27','space_id' => '10011','activity_id' => '27','currency_code' => 'USD','min_hours' => '1','hourly' => '450','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '28','space_id' => '10011','activity_id' => '28','currency_code' => 'USD','min_hours' => '1','hourly' => '450','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '29','space_id' => '10011','activity_id' => '29','currency_code' => 'USD','min_hours' => '1','hourly' => '450','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '30','space_id' => '10012','activity_id' => '30','currency_code' => 'USD','min_hours' => '1','hourly' => '125','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '31','space_id' => '10012','activity_id' => '31','currency_code' => 'USD','min_hours' => '1','hourly' => '125','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '32','space_id' => '10013','activity_id' => '32','currency_code' => 'USD','min_hours' => '1','hourly' => '150','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '33','space_id' => '10013','activity_id' => '33','currency_code' => 'USD','min_hours' => '1','hourly' => '120','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '34','space_id' => '10013','activity_id' => '34','currency_code' => 'USD','min_hours' => '1','hourly' => '170','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '35','space_id' => '10014','activity_id' => '35','currency_code' => 'USD','min_hours' => '1','hourly' => '150','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '36','space_id' => '10014','activity_id' => '36','currency_code' => 'USD','min_hours' => '1','hourly' => '100','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '37','space_id' => '10014','activity_id' => '37','currency_code' => 'USD','min_hours' => '1','hourly' => '200','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '38','space_id' => '10014','activity_id' => '38','currency_code' => 'USD','min_hours' => '1','hourly' => '150','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '39','space_id' => '10014','activity_id' => '39','currency_code' => 'USD','min_hours' => '1','hourly' => '250','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '40','space_id' => '10014','activity_id' => '40','currency_code' => 'USD','min_hours' => '1','hourly' => '120','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '41','space_id' => '10015','activity_id' => '41','currency_code' => 'USD','min_hours' => '1','hourly' => '100','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '42','space_id' => '10015','activity_id' => '42','currency_code' => 'USD','min_hours' => '1','hourly' => '120','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '43','space_id' => '10015','activity_id' => '43','currency_code' => 'USD','min_hours' => '1','hourly' => '150','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '44','space_id' => '10015','activity_id' => '44','currency_code' => 'USD','min_hours' => '1','hourly' => '150','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '45','space_id' => '10016','activity_id' => '45','currency_code' => 'USD','min_hours' => '1','hourly' => '200','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '46','space_id' => '10016','activity_id' => '46','currency_code' => 'USD','min_hours' => '1','hourly' => '150','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '47','space_id' => '10016','activity_id' => '47','currency_code' => 'USD','min_hours' => '1','hourly' => '150','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '48','space_id' => '10016','activity_id' => '48','currency_code' => 'USD','min_hours' => '1','hourly' => '100','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '49','space_id' => '10017','activity_id' => '49','currency_code' => 'USD','min_hours' => '2','hourly' => '100','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '50','space_id' => '10017','activity_id' => '50','currency_code' => 'USD','min_hours' => '1','hourly' => '120','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '51','space_id' => '10018','activity_id' => '51','currency_code' => 'USD','min_hours' => '1','hourly' => '290','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '52','space_id' => '10018','activity_id' => '52','currency_code' => 'USD','min_hours' => '1','hourly' => '290','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '53','space_id' => '10018','activity_id' => '53','currency_code' => 'USD','min_hours' => '1','hourly' => '290','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '54','space_id' => '10018','activity_id' => '54','currency_code' => 'USD','min_hours' => '1','hourly' => '290','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '55','space_id' => '10019','activity_id' => '55','currency_code' => 'USD','min_hours' => '1','hourly' => '90','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
			array('id' => '56','space_id' => '10019','activity_id' => '56','currency_code' => 'USD','min_hours' => '1','hourly' => '90','full_day' => '500','weekly'=>'1000','monthly'=>'2000'),
        ]);

        DB::table('availability_times')->insert([
			array('id' => '1','space_availability_id' => '2','start_time' => '07:00:00','end_time' => '08:00:00'),
			array('id' => '2','space_availability_id' => '9','start_time' => '02:00:00','end_time' => '05:00:00'),
			array('id' => '3','space_availability_id' => '9','start_time' => '08:00:00','end_time' => '21:00:00'),
			array('id' => '4','space_availability_id' => '25','start_time' => '05:00:00','end_time' => '20:00:00'),
			array('id' => '5','space_availability_id' => '26','start_time' => '05:00:00','end_time' => '21:00:00'),
			array('id' => '6','space_availability_id' => '58','start_time' => '00:00:00','end_time' => '05:00:00'),
        ]);
    }
}